set_property IOSTANDARD LVCMOS18 [get_ports {stage[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {stage[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {stage[0]}]
set_property PACKAGE_PIN U14 [get_ports {stage[2]}]
set_property PACKAGE_PIN U19 [get_ports {stage[1]}]
set_property PACKAGE_PIN W22 [get_ports {stage[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports c_in]
set_property IOSTANDARD LVCMOS18 [get_ports done]
set_property IOSTANDARD LVCMOS18 [get_ports input_valve]
set_property IOSTANDARD LVCMOS18 [get_ports lid]
set_property IOSTANDARD LVCMOS18 [get_ports output_drain]
set_property IOSTANDARD LVCMOS18 [get_ports pause]
set_property IOSTANDARD LVCMOS18 [get_ports reset]
set_property IOSTANDARD LVCMOS18 [get_ports start]
set_property PACKAGE_PIN Y9 [get_ports c_in]
set_property PACKAGE_PIN T22 [get_ports done]
set_property PACKAGE_PIN U22 [get_ports input_valve]
set_property PACKAGE_PIN M15 [get_ports lid]
set_property PACKAGE_PIN T21 [get_ports output_drain]
set_property PACKAGE_PIN G22 [get_ports pause]
set_property PACKAGE_PIN H22 [get_ports reset]
set_property PACKAGE_PIN F22 [get_ports start]

create_clock -period 10.000 -name c_in -waveform {0.000 5.000} [get_ports c_in]
set_false_path -from [get_ports reset]